import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

const links = [{
  label: 'Home',
  route: '/'
}, {
  label: 'Login',
  route: '/login'
}, {
  label: 'Crear Cuenta',
  route: '/signUp'
}]

export const metadata: Metadata = {
  title: 'ADA AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul className='navBarList'>
              <a href="/">
                <Image src={"/img/ada_logo.png"} alt='ADA' width={150} height={50} className='logo' />
              </a>
              {links.map(({ label, route }) => (
                <li key={route}>
                  <Link href={route}>{label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <div className='background'>
          <div className='img'>
            <img src="/img/black-background.jpg" alt="" />
          </div>
          <div className='img_overlay'></div>
        </div>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
